
#:kivy 1.11.1
<MainScreen>:
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        canvas.before:
            Color:
                rgba: 0, 1, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        
        Button:
            text:"report"
            on_press: root.on_press_report()

        Button:
            text:"history"
            on_press: root.on_press_history()
    
    